"""Export the data-quality matrix to the website as a compact JS data file.

Reads data_quality_matrix.csv + companies_seed.csv (outputs of run_all.py)
and writes Website/data/coverage.js for the Quant page's coverage explorer.
A .js assignment rather than .json so the page also works opened from disk.

Status codes per field: O = OK (5+ annual periods), T = THIN (<5),
M = MISSING, N = N/A (structurally absent for the sector).
"""
import json
import os
from datetime import date

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.join(HERE, "..", "..", "Website", "DCWebsite", "Website")
OUT = os.path.join(SITE, "data", "coverage.js")

CODES = {"OK": "O", "THIN": "T", "MISSING": "M", "N/A": "N"}

matrix = pd.read_csv(os.path.join(HERE, "data_quality_matrix.csv"), keep_default_na=False)
seed = pd.read_csv(os.path.join(HERE, "companies_seed.csv"), keep_default_na=False)
df = matrix.merge(seed[["ticker", "name", "industry", "company_type"]], on="ticker", how="left")

fields = list(matrix.columns[matrix.columns.get_loc("revenue"):matrix.columns.get_loc("coverage_pct")])

companies = []
for _, r in df.sort_values("ticker").iterrows():
    companies.append([
        r["ticker"], r["name"] or r["ticker"], r["sector"], r["industry"], r["company_type"],
        "".join(CODES[r[f]] for f in fields),
        float(r["coverage_pct"]), r["screenable"] in (True, "True"), int(r["total_concepts"]),
    ])

payload = {"asOf": date.today().isoformat(), "fields": fields, "companies": companies}
os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as fh:
    fh.write("// Generated by DC/scripts/12_export_web.py. Do not edit by hand.\n")
    fh.write("window.DC_COVERAGE = " + json.dumps(payload, separators=(",", ":")) + ";\n")

print(f"wrote {len(companies)} companies x {len(fields)} fields -> {os.path.normpath(OUT)}")
